### ISSUE TITLE
Build fails with libplist 2.2.0 on Linux Mint 21.3 / Ubuntu 22.04

### ISSUE THREAD

**Issue by 1ajh** [tr4m0ryp/iCloud-Bypass-Tool#94]
## Environment

* OS: Linux Mint 21.3 (Ubuntu 22.04 "Jammy")
* Compiler: GCC
* libplist: 2.2.0
* libplist-dev: 2.2.0

```text
$ pkg-config --modversion libplist-2.0
2.2.0

$ dpkg -l | grep libplist
ii  libplist-dev:amd64  2.2.0-6build2
ii  libplist3:amd64     2.2.0-6build2
```

## Problem

The project fails to build on a clean Linux Mint 21.3 installation.

The failure occurs in `include/compat/plist_compat.h`:

```text
include/compat/plist_compat.h: In function ‘tp_plist_mem_free’:
include/compat/plist_compat.h:33:12: warning: implicit declaration of function ‘plist_mem_free’

include/compat/plist_compat.h: In function ‘tp_plist_from_memory’:
include/compat/plist_compat.h:55:16: error: invalid use of void expression
   return (int)plist_from_memory(data, length, out);
```

The build then exits with:

```text
make: *** [Makefile:54: src/activation/session_online.o] Error 1
```

## Observations

The build is defining:

```text
-DTP_PLIST_HAS_MEM_FREE=1
```

However, the compiler reports `plist_mem_free` as an implicit declaration, suggesting the feature detection may be incorrectly identifying the installed libplist API.

Likewise, the compatibility wrapper appears to assume `plist_from_memory()` has a return type that does not match what the installed headers expose.

This makes me think the compile-time feature detection for `TP_PLIST_HAS_MEM_FREE` and/or `TP_PLIST_HAS_FMT_ARG` may be producing incorrect results for libplist 2.2.0.

## Reproduction

1. Install Linux Mint 21.3 (Ubuntu 22.04).
2. Install project dependencies.
3. Run the project's build script or `make`.
4. Observe the compiler errors above.

If there's a required libplist version or a branch intended for Ubuntu 22.04 / Mint 21.x, please let me know.

**Comment by eugene373** [comment]
Reporting the same issue.
